### PR TITLE
New sandbox environment

### PR DESCRIPTION
**Pull request by severin-lemaignan**
Here a proposal for a new, default `sandbox` scene.

sandbox-screenshot

### CODE REVIEW

**Comment by adegroote** [comment]
What do you change in morse_default_autorun.blend ?
Otherwise, it looks pretty nice

**Comment by severin-lemaignan** [comment]
@adegroote The background color (from blue to black)

**Comment by severin-lemaignan** [comment]
Updated the model, to add more objects (cf updated screenshot)

**Comment by adegroote** [comment]
Merged, thanks.

**Comment by pierriko** [comment]
why change the background color and not use `Environment.set_horizon_color` instead ?

**Comment by severin-lemaignan** [comment]
@pierriko Why not doing it? :-) ...and the default blue looked ugly with the new environment.

**Comment by pierriko** [comment]
OK, I see. I whish I had time to debug the `fullpy` PR, we wouldn't have to change .blend for this kind of things.

For some outdoors (not the one in morse/data) environments, the blue gave a light sky effect, without having to add a skybox, but we can still add another horizon color from the builder script.

So nevermind my comment :)

**Pull request closed without merging**
