### PR TITLE
[doc] Update copyright

### PR DESCRIPTION
**Pull request by adegroote**
Add ISAE to the list of copyright handler, as they supported most of the development last year. It is ok for everyone ?

### CODE REVIEW

**Comment by severin-lemaignan** [comment]
To be honest, I'm not sure about the 'right way' here: to the extend of my understanding, the copyright of MORSE doesn't actually belong to LAAS, ONERA or ISAE since we never got any external contributor to sign a [copyright transfer agreement](http://opensource.org/faq#contributor-agreements).

So I would be in favor of removing completely the copyright notices.

@mherrb may have a better picture of the issue, though.

**Comment by adegroote** [comment]
To be fair, I personally don't care at all :)

For CTA, I don't think it is required. I think I signed only two (one for NetBSD, one for JaneStreet) in my all life (FSF requires it also). (and for NetBSD, it is just to become 'developer', not for single patch).

**Comment by mherrb** [comment]
On Thu, Feb 04, 2016 at 01:40:18AM -0800, Séverin Lemaignan wrote:
> To be honest, I'm not sure about the 'right way' here: to the extend of my understanding, the copyright of MORSE doesn't actually belong to LAAS, ONERA or ISAE since we never got any external contributor to sign a [copyright transfer agreement](http://opensource.org/faq#contributor-agreements).
> 
> So I would be in favor of removing completely the copyright notices.

You cannot legally remove the copyright notices. Without a copyright
holder that actually grants the permissions listed in the license, the
license is invalid. As far as I know the Debian project will reject
the package if it has no copyright notice.

> @mherrb may have a better picture of the issue, though.

For people working for some employers, the copyright generally goes to
the employer. This is especially true for french public entities like
LAAS/CNRS, ISAE or ONERA. (there is a special case for interns, but I
don't feel comfortable enough with the legal terms in english to try
to explain it here).

People who work on Morse on their free time or have a specific
agreement with their employer keep their rights.

The full license for MORSE should include all copyright notices of the
various copyright holders.

There are 2 reasons to get contributors to transfer their rights to
some common entity:
 - simplify the license file maintainance (some users are sensitive to
   the FUD around long lists of licenses and copyright notices)
 - have a single entity able to take legal action in case of copyright
   violation or changes to the license terms.

In my opinion it's not worth the trouble.

So to go back to Arnaud's initial question, yes you should add ISAE to
the list of contributors, and an ISAE copyright notice to files you
touched significantly since you started working there...

-- 
Matthieu Herrb

**Comment by adegroote** [comment]
On 04/Feb - 02:39, Matthieu Herrb wrote:
> So to go back to Arnaud's initial question, yes you should add ISAE to
> the list of contributors, and an ISAE copyright notice to files you
> touched significantly since you started working there...

Unfortunately, we never track properly copyright by file. Doing it now
will be very cumbersome. So I guess I will just update the top files, as
proposed in the PR.

**Comment by mherrb** [comment]
On Thu, Feb 04, 2016 at 04:06:33AM -0800, Arnaud Degroote wrote:
> On 04/Feb - 02:39, Matthieu Herrb wrote:
> > So to go back to Arnaud's initial question, yes you should add ISAE to
> > the list of contributors, and an ISAE copyright notice to files you
> > touched significantly since you started working there...
> 
> Unfortunately, we never track properly copyright by file. Doing it now
> will be very cumbersome. So I guess I will just update the top files, as
> proposed in the PR.
> 

Yes. If at some point some users of morse require it, the full
per-file history is in the git repository. It's not too much of a
problem. 

In X.Org, after Oracle bought Sun Microsystems, their legal department
required us to review *all* Sun copyrights in every file through the
project, and potential conflicts. And the Debian project took this
opportunity to ask for a general review of all the contributions. So
someone had to review the history of each file across serveral
different version control systems and several directory hierarchies
to collect all the copyrights and different licenses.

> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/morse-simulator/morse/pull/692#issuecomment-179791937

-- 
Matthieu Herrb

**Comment by severin-lemaignan** [comment]
@mherrb Thanks for the details. Does something like:
`Copyright held by the various authors or the institutions employing them, refer to the AUTHORS file for details` could work?
An additional note could mention: `please refer to the commit history of each file ('git log <file>') to know the exact copyright holders for each file`

**Comment by mherrb** [comment]
On Thu, Feb 04, 2016 at 04:18:31AM -0800, Séverin Lemaignan wrote:
> @mherrb Thanks for the details. Does something like:
> `Copyright held by the various authors or the institutions employing
> them, refer to the AUTHORS file for details` could work? 
> An additional note could mention: `please refer to the commit
> history of each file ('git log <file>') to know the exact copyright
> holders for each file` 

IANAL (I Am Not A Lawyer), but yes I think this can help answering
question that people may ask.

I would write the additional note as 

"Please rever to the commit history of each file ('git log <file>') to
list the contributors to each file."

because the git history lists persons, not organisations (especially
since some people used an email address that doesn't represent their
affiliation).

Having to do a deep audit of the contributors would still be a bit
painful, but it would be a great sign that Morse is a success and that
it gets attention from big actors !
-- 
Matthieu Herrb

**Comment by adegroote** [comment]
So the plan is to add this two lines in LICENSE, or remove "old" copyright which will be superseded by these two sentences ? In case 1, should I modify all the other path ?

**Comment by severin-lemaignan** [comment]
Everywhere 'LAAS/ONERA, LAAS' appears, I would replace by:
```Copyright held by the MORSE authors or the institutions employing them, refer to the AUTHORS file for the list. The list of the contributors to each file can be obtained from the commit history ('git log <file>').```

**Comment by mherrb** [comment]
On Thu, Feb 04, 2016 at 06:13:14AM -0800, Séverin Lemaignan wrote:
> Everywhere 'LAAS/ONERA, LAAS' appears, I would replace by:
> ```Copyright held by the MORSE authors or the institutions employing
> them, refer to the AUTHORS file for the list. The list of the
> contributors to each file can be obtained from the commit history
> ('git log <file>').``` 

I'm not sure the above is a valid copyright notice. Some lawyers seem
to be very picky on the exact form of the notice to consider it
valid (personnaly I find this stupid, but my opinion doesn't count).

I would not change the actual copyright notices in the files in a
hurry before releasing 1.4

Add ISAE to the AUTHORS 

in LICENSE add 

Copyright (c) 2014-2015  ISAE-SUPAERO (or whatever is the correct
name)

and then the sentence above.

It is perfectly legit to have several Copyright lines in one file.

Then after 1.4 take the time to get more knowledgeable advice and 
edit the individual notices in files accordingly if needed.

> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/morse-simulator/morse/pull/692#issuecomment-179858572

-- 
Matthieu Herrb

**Comment by severin-lemaignan** [comment]
Fine for me.

**Comment by adegroote** [comment]
Does it look good for you now ? I'm not completely sure for one in conf.py.in, the generated footer is really ugly.

**Comment by severin-lemaignan** [comment]
If for the minor comment above, good for me (for now at least).

**Comment by mherrb** [comment]
On Fri, Feb 05, 2016 at 01:19:40AM -0800, Séverin Lemaignan wrote:
> If for the minor comment above, good for me (for now at least).

You decide at the end but I think that it's confusing the way you've
written it. I would have put:

Copyright © 2009-2010 ONERA
Copyright © 2009-2016 CNRS-LAAS
Copyright © 2015-2016 ISAE-SUPAERO

Which is more in-line with the way other projects do it (see for
instance http://cgit.freedesktop.org/xorg/xserver/tree/COPYING)
-- 
Matthieu Herrb

**Comment by adegroote** [comment]
New try for the copyright stuff

**Comment by severin-lemaignan** [comment]
+1

**Comment by adegroote** [comment]
Merged in  commit 5516c10d

**Pull request closed without merging**
