### PR TITLE
Several ROS related (minor) fixes

### LINKED ISSUE #645: ROS middleware use some outdated / inexistant messages
The doc generation reveals that the following messages does not exist anymore in Indigo

- asctec_msgs
- motion_control_msgs

It will be nice to provide an alternative 'modern' implementation for this types, and a way to use the old type for old ROS release, and new types for 'modern' ROS release.

### PR DESCRIPTION
**Pull request by severin-lemaignan**
Should fix #645

### CODE REVIEW

**Comment by adegroote** [comment]
Looks good, at least from a syntactic point of view (still don't have a ROS environment). 
We probably can kill ros.helpers as there is no more user. If we do that, it seems there is no more direct reference to rospkg, so do we still need py3-rospkg ?

Another question : do we always need the copy of tfMessage in tree ?

**Comment by severin-lemaignan** [comment]
@adegroote both your questions are good! To get rid of rospkg would be nice, indeed. I do not see any reason for keeping it, so let's remove it for now.

Regarding `tfMessage`: the ROS-provided Python bindings for `tfMessage.msg` (ie, `tfMessage.py`) are Py3 compliant since a while. *But* `from tf.msg import tfMessage` fails for me as the package `tf` attempts to load a `_tf.so` that fails with Py3.

So for now, we should keep shipping our own `tfMessage` even if it is stupid. I've updated it to the current version, though, and I've also added a simple unit-test.

**Comment by adegroote** [comment]
OK. Nothing to do on the tf side but waiting that Ubuntu and ROS distribute stuff for python3 by default :) Looks good for me to merge. It would maybe nice to add a note in changelog too.

**Comment by severin-lemaignan** [comment]
Merged! (and one open bug less ;-)

**Pull request merged**
