### PR TITLE
Serval modification for Windows

### PR DESCRIPTION
**Pull request by maxint**
Development environment

- Blender v2.75.0
- Python 3.4.2

### CODE REVIEW

**Comment by adegroote** [comment]
Thanks for your patch and all contributions to fix Windows status. Can you tell us how Morse works with all this fixes ?

**Comment by maxint** [comment]
```
In [1]: import os

In [2]: os.uname()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-691df8a3e957> in <module>()
----> 1 os.uname()

AttributeError: 'module' object has no attribute 'uname'
```

**Comment by maxint** [comment]
The `morse run` could not work in Windows right now. The issue is reported in [](https://github.com/morse-simulator/morse/pull/597). I tried the simulation scripts with blender manually.

`vim mysim/morse_run.py`
```
import sys
sys.path.append('C:/Windows/system32/python34.zip')
sys.path.append('D:/Python34/DLLs')
sys.path.append('D:/Python34/lib')
sys.path.append('D:/Python34')
sys.path.append('D:/Python34/lib/site-packages')
sys.path.append('f:/code/morse/src')
sys.path.append('f:/code/morse/bindings/pymorse/src')
#sys.path.append('C:/morse/bin')
#sys.path.append('C:/morse')
#sys.path.append('C:/morse/Lib/site-packages')
sys.path.append('f:/projects/ar/morse-test/mysim/src')
exec(compile(open('f:/morse-test/mysim/irobot.py').read(), 'f:/morse-test/mysim/irobot.py', 'exec'), globals (), locals ()) 
```
`vim mysim/morse_run.bat`
```
@echo off
"c:\Program Files (x86)\Blender Foundation\Blender\blender.exe" f:\code\morse\data\morse_default_autorun.blend -P morse_run.py -- with-colors 
```

**Comment by adegroote** [comment]
I merged your pull-request after merging some related commit and "improved" some commit messages. Thanks for your help and your contribution. 

Moreover, I opened a meta-issue #641 to track Windows specific issue and pull-request.

**Comment by maxint** [comment]
Thanks, I will be watching this issue.

**Pull request closed without merging**
