### PR TITLE
Added a template for filling issues

### PR DESCRIPTION
**Pull request by severin-lemaignan**
Following its introduction by github: https://github.com/blog/2111-issue-and-pull-request-templates

### CODE REVIEW

**Comment by pierriko** [comment]
:+1:

**Comment by adegroote** [comment]
I'm not sure it is really useful, as most of issues in the Morse project are some feature request or things to add.
At least, add it in the .github/ directory to not pollute more the root directory.

**Comment by severin-lemaignan** [comment]
@adegroote Well, I agree, it is not very useful :-) But it does not hurt either, does it? :-)
I've moved it to `.github` and I'll merge it in 15min: Let me know you want to add other items to the template.

**Comment by severin-lemaignan** [comment]
Here we are:
https://github.com/morse-simulator/morse/issues/new

**Pull request merged**
