### PR TITLE
Cleanup camera and fbo

### PR DESCRIPTION
**Pull request by adegroote**

### CODE REVIEW

**Comment by adegroote** [comment]
I upgraded the branch to consider your remarks. Tell me if it is good for you. Do we merge it now even if fbo stuff is still not in blender master branch ?

**Comment by pierriko** [comment]
Looks good, I have no time to test today, you can merge, I'll have a better look later this week

**Comment by severin-lemaignan** [comment]
@adegroote I'm fine with merging (as I'm pretty confident that the upstream changes are going to be merged at some point), but it would be useful to give a bit of context in the commit message (basically, a link to the upstream issue and one sentence about why FBO are useful to us).

Btw, I wonder if we shouldn't mention FBO rendering in the documentation of the VideoCamera sensor as well...

**Comment by adegroote** [comment]
> Btw, I wonder if we shouldn't mention FBO rendering in the documentation of the VideoCamera sensor as well...

I don't think, it is really a detail of implementation (and probably the good / best way to do that in OpenGL :D).

**Comment by adegroote** [comment]
Merged after edition of the second commit message

**Pull request closed without merging**
