### PR TITLE
Cleanup wheeled robot

### PR DESCRIPTION
**Pull request by adegroote**
This set of commits simplify a lot wheeled robots, and kill some non-needed specificities. It prepares terrain for different kind of PhysicalRobot.

### CODE REVIEW

**Comment by adegroote** [comment]
Can I assume I can merge it after integrating your comment fix ?

**Comment by severin-lemaignan** [comment]
Well, I'm not familiar with this part of MORSE... Maybe @pierriko can give it a better look?

**Comment by pierriko** [comment]
I'll have a look during the day

**Comment by pierriko** [comment]
It's OK for me.

The robot tests might need some fix, but they were already broken.
`testing/robots/segway/two_segways.py` passes, others fails, but no changes.
Pioneer3DX test still fails as well.

```
======================================================================
FAIL: test_vw_controller (__main__.Pioneer3DXTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testing/robots/pionner3dx/pionner3dx_testing.py", line 73, in test_vw_controller
    self.assertAlmostEqual(coord, 0.0, delta=0.05)
AssertionError: 0.1233196035027504 != 0.0 within 0.05 delta

======================================================================
FAIL: test_vw_controller (__main__.Pioneer3DXTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testing/robots/pionner3dx/pionner3dx_testing.py", line 73, in test_vw_controller
    self.assertAlmostEqual(coord, 0.0, delta=0.05)
AssertionError: 0.09353667497634888 != 0.0 within 0.05 delta

----------------------------------------------------------------------
```

**Comment by adegroote** [comment]
I know about pionner test (but the situation is the same in 1.4). It seems to work by applying an initial rotation (like -0.10 radian on yaw) through I don't committed this hack :) I don't understand yet from where come this rotation.

**Comment by adegroote** [comment]
Merged

**Pull request closed without merging**
