### PR TITLE
Extended keyboard

### PR DESCRIPTION
**Pull request by cehberlin**
Created a new clean request for existing #656. Moreover this pull request includes extensions to the former request.

### CODE REVIEW

**Comment by severin-lemaignan** [comment]
Your pull-request looks better, but I'm not sure about 3d9274a: If you rebase your PR on top of master, you should not need that.

By the way, you do not need to create a new pull request everytime: you can just 'force' push your new changes with ``git push -f`` to update your PR.

**Comment by cehberlin** [comment]
You are right with  3d9274a and rebase, but I copied over the file from 1.3 where I made my changes, thus I corrected this manually afterwards. I hope this is ok.

**Comment by severin-lemaignan** [comment]
@cehberlin well, no :-) What you need to do is to *squash* the two commits together. You can use ``git rebase -i HEAD~2`` for that (replacing ``pick`` in front of the last commit by ``squash`` or ``fixup``) and then ``git push -f`` to update your PR.

**Comment by cehberlin** [comment]
Thanks for the instructions, I have never used this git feature,it is quite useful. I hope you are satisfied now.

**Comment by adegroote** [comment]
I don't have particular opinion on this commit, looks ok for me. If severin is ok I will merge it.

**Comment by severin-lemaignan** [comment]
I'm still convince about changing the default behaviour of arrow keys, but it's not a big big deal either. Let's merge it, and if needed, we'll change back the rotate vs strafe behaviour.

**Comment by pierriko** [comment]
... to come back on this topic, I think the best place for robot control would be in a client behind a middleware.
It might sound a bit overkill for keyboard/debug, but that's what makes the simulator modular. If we tweak to much the internals, it kinds of loose its concept.

**Comment by adegroote** [comment]
I tend to agree with @pierriko

**Comment by severin-lemaignan** [comment]
Merge, but I've kept the previous bindings for turn left/turn right (ie, no behaviour change for the arrow keys).

Left/right strafe is U/O.

Thanks!

**Pull request closed without merging**
