### PR TITLE
Updates middleware, tests, and docs to support new MOOS interface

### LINKED ISSUE #752: MOOS new python interface
What is the best practice to update a middleware?

`MOOS` has now an official interface for [python](https://github.com/themoos/python-moos) and I want to contribute with a new interface to MORSE, but afraid if I replace the existing one by @davidhodo through a PR, it might ruin legacy code.

Should we have a `MOOS2` (or even `MOOSv10` as the creator likes to call it) interface in this case?

### PR DESCRIPTION
**Pull request by msis**
This closes #752 .

### CODE REVIEW

**Comment by pierriko** [comment]
Couldn't test, but it looks very good ! Thanks :+1:

**Comment by msis** [comment]
Thanks @pierriko ,
The documentation has been updated accordingly to allow whomever is interested to try and test.

I'm thinking of a way to add unit tests in, but I need the script to install and launch MOOS. Any ideas on how to do that?

**Comment by pierriko** [comment]
You could create a MoosTestCase class. Have a look at this example testing a Sick LiDAR on ROS:
https://github.com/morse-simulator/morse/blob/master/testing/middlewares/ros/sick.py
using: https://github.com/morse-simulator/morse/blob/master/src/morse/testing/ros.py

**Comment by msis** [comment]
That's cool!
I will give it a try and create another PR.

**Comment by msis** [comment]
@pierriko , I have added a test now.
What's the plan now to merge it?

**Comment by pierriko** [comment]
Everything looks good, could you squash the `[mw/moos]` commits together (using `git rebase -i`) ? Same thing for `[testing]`. And remove the merge commit.

Thanks!

**Comment by msis** [comment]
I thaught it was good to have different commits so future devs would know how to write their interfaces.
I will start rebasing soon. I have an idea about the default publisher that I want to try first. I may include it too.

**Comment by msis** [comment]
Alright, `git rebase`d and tested !
Thanks for accepting the PR!

**Comment by pierriko** [comment]
Merged, Thanks!

**Pull request merged**
