### PR TITLE
Initial version of the morse_sync tool

### PR DESCRIPTION
**Pull request by adegroote**
Initial version of morse_sync to handle #683, mostly for discussion.

What to handle yet:
  - add a man-page (easy part)
  - understand argparse API so it reports an error when some arguments are missing
 - add a way to communicate / control it (if we want automatic adjustment of fps (see #687)). I was thinking about a named pipe (old-style unix user), but it seems there is no way to do that in a portable way in python (WTF!! ;D). Any through ?

### CODE REVIEW

**Comment by severin-lemaignan** [comment]
For IPC communication, stdin/stdout pipes provided by subprocess wouldn't do?

**Comment by severin-lemaignan** [comment]
otherwise, the most robust & cross-platform way is probably a pair of TCP sockets...

**Comment by adegroote** [comment]
Added a man-page, a "parsing" of stdin, and a mechanism to auto-launch it. Please review.

**Comment by severin-lemaignan** [comment]
Before I review the last commits, see my lenghty comment in #683

**Comment by adegroote** [comment]
The branch now contains some other time-related commit to Morse, in particular af4b0ae, which fix your issue about frequency handling. I'm now searching the "best default setting" for Morse, but this set of commit should improve a lot the situation anyway. We should hurry a bit if we want to integrate Ubuntu 16.04.

**Comment by severin-lemaignan** [comment]
One of the issue that makes the whole 'time management' thing difficult to grasp is the vocabulary. So far, we are not very consistent, and not always using the correct terminology. I propose to use the following terminology:

- `bpymorse.set_speed` method should be renamed in `set_simulator_base_frequency` (or shorter, `base_frequency`)
- `fps` should only be used when we discuss, well, 'frames per second'. Since for a simulator, the 'video frames per second' should not be important, this should be instead replaced by `loops_per_second` or something similar
- `time factor` and `time scale` must be unified. An 'easy' option is to use `speed`
- `set_time_scale` could become `set_simulation_speed` (or shorter `simulation_speed`)

**Comment by adegroote** [comment]
Handle some of change discussed previously. I also add an 'time_auto_tune', which tries to autoconf Morse time settings (must handle case {1, 3, 4, 5}).

**Comment by adegroote** [comment]
use_vsync('OFF')
use_internal_syncer()

seems a good default, but break some tests. Need to investigate the cause

**Comment by adegroote** [comment]
After more test, vsync = off + use_internal_syncer + best effort works fine, so I put it in default configuration. vsync_off + use_internal_syncer + fixedtimestep breaks a lot of tests. I'm not sure to understand why. Through, it will an "advanced" settings. 

If ok with the current code, I will update the documentation. I'm not sure about the need of 40a850bab6b5fcce954c136ea3cc71828d6182ed now that most scenario are covered automatically.

**Comment by severin-lemaignan** [comment]
Ok for me to drop 40a850b for now. We'll see if the need arise later.

**Comment by adegroote** [comment]
I think the branch is complete now. Can you check it a last time before merge ?

**Comment by adegroote** [comment]
Well, you want  I restore the "user part", and I point to the great detail in the dev page :)

**Comment by severin-lemaignan** [comment]
I guess a user part would make sense, yes :-)

**Comment by adegroote** [comment]
Does the changes proposed 2 days ago handle your remarks ?

**Comment by adegroote** [comment]
Just updated last two commits with your comments

**Comment by severin-lemaignan** [comment]
Then, let's merge it! :-)

**Comment by adegroote** [comment]
Merged.

**Comment by severin-lemaignan** [comment]
\o/

**Pull request closed without merging**
