### PR TITLE
[doc] Give specific colors to the different MW tags + improve Feature Ma...

### PR DESCRIPTION
**Pull request by severin-lemaignan**
...trix generation and rendering

### CODE REVIEW

**Comment by severin-lemaignan** [comment]
Note that I've also changed the order of middlewares in the Feature matrix to roughly reflect user base (ie, ROS > YARP > socket > pocolibs > MOOS > HLA > text). This is of course open to discussion, I don't want to hurt any feelings ;-)

**Comment by adegroote** [comment]
I don't care very much, through I think socket should be first, as it is extensively used in tutorials / tests (and probably have an important user base). Otherwise, it is ok.

**Comment by severin-lemaignan** [comment]
Ok, fixed.

**Comment by adegroote** [comment]
Done.

**Pull request closed without merging**
