### PR TITLE
Corrected/improved the English in many places etc.

### PR DESCRIPTION
**Pull request by mark-summerfield**
Note: I will not user super() since that's controversial & I will not change MORSE, Morse, or morse:-)

I think line 15 "comment the code" is silly and should be deleted.

### CODE REVIEW

**Comment by severin-lemaignan** [comment]
@mark-summerfield I assume you are making these updates via the Github online editor, right? Creating one pull-request per change is not very nice on our end :-) It took me ~1 hour yesterday to rebase all your changes into a single branch, and then squash them into one commit.

If you are a confident git user, please make all your changes in the same branch and submit one PR (that you might want to update everytime you make more changes).

If you do not know git very well and prefer to use the online editor, please commit to your `master` branch (by selecting the corresponding option when committing) and then create a single PR. Every subsequent changes to your master branch will be automatically added to that pull request.

**Comment by mark-summerfield** [comment]
Hi Séverin,

On Thu, 27 Oct 2016 01:31:19 -0700
Séverin Lemaignan <notifications@github.com> wrote:
> @mark-summerfield I assume you are making these updates via the Github
> online editor, right? Creating one pull-request per change is not very
> nice on our end :-) It took me ~1 hour yesterday to rebase all your
> changes into a single branch, and then squash them into one commit.
> 
> If you are a confident git user, please make all your changes in the
> same branch and submit one PR (that you might want to update everytime
> you make more changes).
> 
> If you do not know git very well and prefer to use the online editor,
> please commit to your `master` branch (by selecting the corresponding
> option when committing) and then create a single PR. Every subsequent
> changes to your master branch will be automatically added to that pull
> request.
 
I am doing them one at a time using Github.

I'd rather do them on my own machine so I could use vim.

But I only know how to use mercurial (and that not very well).

Couldn't I do a "git clone" and then make my changes locally and then
push them to you? If this is possible, it would help if you'd give me
the commands to use. My OS is Ubuntu 16.04 and I have or can easily
install git or any other tool I'd need.

So, I'll stop for now!

-- 
Mark Summerfield, Qtrac Ltd.
    XindeX - easy to learn and use software for creating book indexes
        http://www.qtrac.eu/xindex.html

**Comment by severin-lemaignan** [comment]
@mark-summerfield so, in brief:
- install `git` if needed (`sudo apt install git`)
- clone MORSE somewhere:
```
$ git clone https://github.com/mark-summerfield/morse.git
```
- then:
```sh
$ cd morse
# create a branch
$ git checkout -b language_fixes
# make all the changes you want and commit them all:
$ git commit -a -m"[doc] More English fixes"
# make more changes and commit again as often as you want
# Then, once you want to share:
$ git push --set-upstream origin language_fixes
# (the --set-upstream is only needed the first time)
```

Now, from [your Github MORSE fork](https://github.com/mark-summerfield/morse), you can create a pull request for us.

If you do more changes, just commit and push again to the same `language_fixes`, it will update the pull request automatically.

Let me know if this works for you!

**Comment by dgerod** [comment]
@mark-summerfield , what is the current situation? Are you doing what @severin-lemaignan said? 

Thanks.

**Comment by mark-summerfield** [comment]
No, I'm not doing any more. I had a window of time a while back where I did a bunch of doc fixes, but no longer have that time.

**Pull request closed without merging**
